### ISSUE TITLE
units and pints issue in latest version

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#75]
Hi Tanguy,
I'm finalyy running on the lastest master version... well, actually not.  I cannot resolve issues with units in my codes and examples that load environments. Issues risen concern units and Pint. I definitively have the latest pint, reinstalled indeed all the required libraries.

Apparently some commands seed.neurons() now require explicit indication of the unit (implies we have to correct all the exmaple files !) but this is not enough.

See for instance the output of the example

```
python circular_simple.py 
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:172: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._parent           = None
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:173: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._unit             = unit
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:174: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._geom_type        = g_type
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:175: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._return_quantity = False
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1053: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._parent          = None
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1054: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._unit            = unit
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1055: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._geom_type       = g_type
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1057: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._area            = None
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1058: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj.height           = height
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1059: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj.name             = name
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1060: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._prop            = _PDict(
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:1062: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._return_quantity = False
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:176: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  obj._areas = {
/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py:317: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
  disk.radius = radius
Traceback (most recent call last):
  File "/home/ele/Documents/WORK/DENSE/examples/space_embedding/circular/circular_simple.py", line 132, in <module>
    neuron_params['position'] = culture.seed_neurons(
  File "/home/ele/.local/lib/python3.10/site-packages/dense-0.1.0-py3.10-linux-x86_64.egg/dense/environment/shape.py", line 827, in seed_neurons
    raise RuntimeError("`return_quantity` requested but Pint is "
RuntimeError: `return_quantity` requested but Pint is not available. Please install it first.
```

I do not understand also  the new argument 'return_quantity', when I change the code to set it to false set to False, the issue is with
reate_neurons()

```
Creating neurons
Traceback (most recent call last):
  File "/home/ele/Documents/WORK/20210507/Improving_density_plot/arches-work.py", line 158, in <module>
    gids = ds.create_neurons(n=num_neurons,
  File "_pygrowth.pyx", line 327, in dense._pygrowth.create_neurons
  File "_pygrowth.pyx", line 1796, in dense._pygrowth._create_neurons
  File "_pygrowth.pyx", line 2289, in dense._pygrowth._set_vector_status
AssertionError: Positions must have units.
```
Well I stuck and cannot even revert to previous versions...
Thank you for your suggestions

Samuel

**Comment by tfardet** [comment]
Pint has been updated and requires to update the `environment` folder to support the latest version via ``git submodule update --remote --merge``
