### ISSUE TITLE
Issue with Pint

### ISSUE THREAD

**Issue by SBottani** [SENeC-Initiative/DeNSE#76]
Hi Tanguy,

I'm reinstalling the latest master on a fully updated system (Debian); Dense installs but I cannot run my code any longer, because of some issue with Pint

```
  self._areas     = {
Traceback (most recent call last):
  File "/home/bottani/2021_Arches_fig/arches2_figure/Temp_RIGHT/temp.py", line 161, in <module>
    pos = culture.seed_neurons(neurons=num_neurons,
  File "/home/bottani/.local/lib/python3.9/site-packages/dense-0.1.0-py3.9-linux-x86_64.egg/dense/environment/shape.py", line 848, in seed_neurons
    raise RuntimeError("`return_quantity` requested but Pint is "
RuntimeError: `return_quantity` requested but Pint is not available. Please install it first.
```

Of ourse 'Pint' is installed

```
In [1]: import pint

In [2]: print(pint.__version__)
0.18
```

There are also many warning concerning `Shapely` when shapely objects are used,  as

```
 self._geom_type = 'Polygon'
/home/bottani/.local/lib/python3.9/site-packages/dense-0.1.0-py3.9-linux-x86_64.egg/dense/environment/shape.py:418: ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0
```

Having I think upgraded all requirements and packages I am at a loss here.
Thank you

Samuel

**Comment by tfardet** [comment]
I think this is an issue with your pint version being too old, can you run ``pip install --upgrade pint`` and check again?

**Comment by tfardet** [comment]
For the warnings, these have also been fixed as far as I remember, run ``git submodule update --remote --merge``

**Comment by SBottani** [comment]
well, that is not the reason. Now I have the right 0.19.2 pint version and still not working
sumbodule updated also
:-(
